version: '3'

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pg-data:/var/lib/postgresql/db-data

  redis:
    image: redis

  web:
    build: .
    ports:
      - '8080:8080'
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: 'db'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'postgres'
      REDIS_URL: 'redis://redis:6379/'
      WAIT_FOR: 'db:5432 redis:6379'

volumes:
  pg-data:
