# noinspection PyUnresolvedReferences
from .settings import *  # noqa: F401, F403

# NB: use of settings_dev is DEPRECATED
# This is for legacy compatibility only, DO NOT EDIT THIS FILE
# Do not use this. Use "project.settings" with a ".env" file instead.
